# Generated by Django 5.2.4 on 2025-08-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iot_object_mac", models.CharField(max_length=100)),
                ("command", models.CharField(max_length=50)),
                ("user_id", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "coordinators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="departments",
                        to="profiles.coordinator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms_administered",
                        to="profiles.admin",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="resources.department",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="rooms_accessed", to="profiles.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IOTObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, default="Esperando", max_length=50),
                ),
                ("mac", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(default="Porta", max_length=100)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="iot_objects",
                        to="resources.room",
                    ),
                ),
            ],
        ),
    ]
