# Generated by Django 5.2.4 on 2025-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddField(
            model_name='room',
            name='special_coordinators',
            field=models.ManyToManyField(blank=True, related_name='special_rooms_coordinated', to='profiles.coordinator'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponivel'), ('Ocupada', 'Ocupada'), ('Em Manutenção', 'Manutencao')], default='Disponível', max_length=20),
        ),
        migrations.AlterField(
            model_name='iotobject',
            name='status',
            field=models.CharField(blank=True, default='Aguardando Conexão', max_length=50),
        ),
    ]
